name: Test API

on:
  push:
    branches: [main]
    paths:
      - "packages/decent-offchain/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/decent-offchain/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/decent-offchain

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Setup onchain database schema
        run: bun push:onchain
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      - name: Setup offchain database schema
        run: bun push:offchain
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      - name: Setup onchain database data
        run: bun run test/dao.data.ts
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      - run: bun run test
        env:
          ALCHEMY_RPC_ENDPOINT: /v2/
          ALCHEMY_NFT_ENDPOINT: /nft/v3/
          ALCHEMY_URL_8453: https://base-mainnet.g.alchemy.com
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          TEST_PRIVATE_KEY_1: ${{ secrets.TEST_PRIVATE_KEY_1 }}
          TEST_PRIVATE_KEY_2: ${{ secrets.TEST_PRIVATE_KEY_2 }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
