name: Test API

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/decent-offchain/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/decent-offchain/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/decent-offchain

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Setup database schema
        run: bun push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      - name: Setup database schema
        run: psql postgresql://postgres:postgres@localhost:5432/test < test/dao.schema.sql
      - name: Setup database data
        run: psql postgresql://postgres:postgres@localhost:5432/test < test/dao.data.sql
      - run: bun test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
